In [4]:
import torch

In [5]:
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [6]:
x.shape

torch.Size([12])

In [7]:
x.numel()

12

In [8]:
x = x.reshape(3, 4)
x

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [9]:
torch.zeros((2, 3, 4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [10]:
torch.tensor([[2, 2, 3, 4], [1, 2, 3, 4], [5, 5, 5, 6]])

tensor([[2, 2, 3, 4],
        [1, 2, 3, 4],
        [5, 5, 5, 6]])

In [13]:
x = torch.tensor([[[2, 2, 3, 4], [1, 2, 3, 4], [5, 5, 5, 6]]])
x

tensor([[[2, 2, 3, 4],
         [1, 2, 3, 4],
         [5, 5, 5, 6]]])

In [14]:
x.shape

torch.Size([1, 3, 4])

In [15]:
x = torch.tensor([[[[2, 2, 3, 4], [1, 2, 3, 4], [5, 5, 5, 6]]]])
x

tensor([[[[2, 2, 3, 4],
          [1, 2, 3, 4],
          [5, 5, 5, 6]]]])

In [16]:
x.shape

torch.Size([1, 1, 3, 4])

In [17]:
x = torch.tensor([[[2, 2, 3, 4], [1, 2, 3, 4], [5, 5, 5, 6]], [[2, 2, 3, 4], [1, 2, 3, 4], [5, 5, 5, 6]]])
x

tensor([[[2, 2, 3, 4],
         [1, 2, 3, 4],
         [5, 5, 5, 6]],

        [[2, 2, 3, 4],
         [1, 2, 3, 4],
         [5, 5, 5, 6]]])

In [18]:
x = torch.tensor([[[[2, 2, 3, 4], [1, 2, 3, 4], [5, 5, 5, 6]], [[2, 2, 3, 4], [1, 2, 3, 4], [5, 5, 5, 6]]], [[[2, 2, 3, 4], [1, 2, 3, 4], [5, 5, 5, 6]], [[2, 2, 3, 4], [1, 2, 3, 4], [5, 5, 5, 6]]]])
x

tensor([[[[2, 2, 3, 4],
          [1, 2, 3, 4],
          [5, 5, 5, 6]],

         [[2, 2, 3, 4],
          [1, 2, 3, 4],
          [5, 5, 5, 6]]],


        [[[2, 2, 3, 4],
          [1, 2, 3, 4],
          [5, 5, 5, 6]],

         [[2, 2, 3, 4],
          [1, 2, 3, 4],
          [5, 5, 5, 6]]]])

In [19]:
x.shape

torch.Size([2, 2, 3, 4])

In [22]:
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])
x + y, x - y, x * y, x / y, x ** y

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

写1.0表示创建的是浮点数数组

In [23]:
torch.exp(x)

tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])

In [26]:
X = torch.arange(12, dtype=torch.float32).reshape(3, 4)
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [32]:
X = torch.arange(12, dtype=torch.float32).reshape(3, 4)
Y = torch.tensor([[2, 2, 3, 1], [3, 4, 4, 2], [6, 6, 6, 6]])
torch.cat((X, Y), dim=0), torch.cat((X, Y), dim=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  2.,  3.,  1.],
         [ 3.,  4.,  4.,  2.],
         [ 6.,  6.,  6.,  6.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  2.,  3.,  1.],
         [ 4.,  5.,  6.,  7.,  3.,  4.,  4.,  2.],
         [ 8.,  9., 10., 11.,  6.,  6.,  6.,  6.]]))

In [33]:
x2 = torch.tensor([[[2, 2, 3, 1], [3, 4, 4, 2], [6, 6, 6, 6]], [[2, 2, 3, 1], [3, 4, 4, 2], [6, 6, 6, 6]]])
x2

tensor([[[2, 2, 3, 1],
         [3, 4, 4, 2],
         [6, 6, 6, 6]],

        [[2, 2, 3, 1],
         [3, 4, 4, 2],
         [6, 6, 6, 6]]])

In [34]:
x2.shape

torch.Size([2, 3, 4])

In [35]:
y2 = torch.arange(24).reshape(2, 3, 4)
y2

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

In [36]:
torch.cat((x2, y2), dim=0)

tensor([[[ 2,  2,  3,  1],
         [ 3,  4,  4,  2],
         [ 6,  6,  6,  6]],

        [[ 2,  2,  3,  1],
         [ 3,  4,  4,  2],
         [ 6,  6,  6,  6]],

        [[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

In [37]:
torch.cat((x2, y2), dim=1)

tensor([[[ 2,  2,  3,  1],
         [ 3,  4,  4,  2],
         [ 6,  6,  6,  6],
         [ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[ 2,  2,  3,  1],
         [ 3,  4,  4,  2],
         [ 6,  6,  6,  6],
         [12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

In [38]:
torch.cat((x2, y2), dim=2)

tensor([[[ 2,  2,  3,  1,  0,  1,  2,  3],
         [ 3,  4,  4,  2,  4,  5,  6,  7],
         [ 6,  6,  6,  6,  8,  9, 10, 11]],

        [[ 2,  2,  3,  1, 12, 13, 14, 15],
         [ 3,  4,  4,  2, 16, 17, 18, 19],
         [ 6,  6,  6,  6, 20, 21, 22, 23]]])

In [39]:
X == Y

tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [40]:
X.sum()

tensor(66.)

In [41]:
a = torch.arange(3).reshape(3, 1)
b = torch.arange(2).reshape(1, 2)
a, b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [42]:
a + b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

In [43]:
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [44]:
X[-1]

tensor([ 8.,  9., 10., 11.])

显示最后一行

In [45]:
X[1:3]

tensor([[ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [46]:
X[1:2]

tensor([[4., 5., 6., 7.]])

In [47]:
X[0:2]

tensor([[0., 1., 2., 3.],
        [4., 5., 6., 7.]])

In [48]:
X[0:3]

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [49]:
X[0:3:2]

tensor([[ 0.,  1.,  2.,  3.],
        [ 8.,  9., 10., 11.]])

In [50]:
X[::2]

tensor([[ 0.,  1.,  2.,  3.],
        [ 8.,  9., 10., 11.]])

In [51]:
X[1, 2] = 9
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  9.,  7.],
        [ 8.,  9., 10., 11.]])

In [52]:
id(X)

140278241826512

In [53]:
id(X[0, 0])

140278248992016

In [54]:
id(X[2, 2])

140278248991136

In [55]:
id(X[1, 1])

140278248991376

In [56]:
id(X[1, :])

140278248991536

In [57]:
id(X[0, :])

140278248991536

In [58]:
id(X[0, 2])

140278248991856

In [59]:
Y

tensor([[2, 2, 3, 1],
        [3, 4, 4, 2],
        [6, 6, 6, 6]])

In [60]:
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  9.,  7.],
        [ 8.,  9., 10., 11.]])

In [61]:
before = id(Y)
before

140278241872928

In [63]:
Y += X
id(Y)

140278248989296

In [64]:
Y

tensor([[ 2.,  4.,  7.,  7.],
        [11., 14., 22., 16.],
        [22., 24., 26., 28.]])

In [65]:
Z = torch.zeros_like(Y)
Z

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [66]:
id(Z)

140278248964160

In [67]:
Z[:] = X + Y
Z

tensor([[ 2.,  5.,  9., 10.],
        [15., 19., 31., 23.],
        [30., 33., 36., 39.]])

In [68]:
id(Z)

140278248964160

In [69]:
id(X), id(Y)

(140278241826512, 140278248989296)

In [70]:
Y[:] = Y + X

In [71]:
id(Y)

140278248989296

用[:]就不改变地址（原地操作）

In [73]:
X_id = id(X)
Y_id = id(Y)
X_id, Y_id

(140278241826512, 140278248989296)

In [74]:
X += Y
id(X) == X_id

True

用+=也是原地操作

In [75]:
A

NameError: name 'A' is not defined

In [76]:
A = X.numpy()

In [77]:
B = torch.tensor(A)

In [78]:
type(A), type(B)

(numpy.ndarray, torch.Tensor)

可以将大小为1的张量转变为标量

In [79]:
a = torch.tensor([3.5])
a

tensor([3.5000])

In [80]:
a, a.item(), float(a), int(a)

(tensor([3.5000]), 3.5, 3.5, 3)

In [81]:
b = torch.tensor([1.3, 2])
b

tensor([1.3000, 2.0000])

In [85]:
b.item()

ValueError: only one element tensors can be converted to Python scalars

In [83]:
for item in b:
    print(item)

tensor(1.3000)
tensor(2.)


In [86]:
for item in b:
    item