In [2]:
import torch

In [3]:
x = torch.arange(4.0)

In [4]:
x

tensor([0., 1., 2., 3.])

In [5]:
x.requires_grad_(True)
x.grad

In [6]:
y = 2 * torch.dot(x, x)
y

tensor(28., grad_fn=<MulBackward0>)

In [8]:
y.backward()
x.grad

tensor([ 0.,  4.,  8., 12.])

In [9]:
x.grad.zero_() # 把梯度清零 不然会累加
y = x.sum()
y.backward()
x.grad

tensor([1., 1., 1., 1.])